name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          state-name: ftp-deploy-main
          local-dir: ./
          server-dir: /public_html
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            vendor/**
            storage/logs/**
            storage/framework/**
            public/storage/**
            public/build/**
            build/**
            .env
            .env.*

      - name: Run Laravel deployment commands over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script_stop: true
          script: |
            cd /home/u365930992/domains/breem.site/public_html
            if [ -d .git ]; then
              git fetch origin main
              git reset --hard origin/main
            else
              echo "Skipping git pull because no .git directory was found"
            fi
            php artisan down || true
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-dev --optimize-autoloader --no-interaction
            php artisan optimize:clear
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
