@extends('admin.layouts.master')
@section('content')
    <div class="page-wrapper">
        @include('admin.layouts.sidebar')
        <div class="page-content">
            @include('admin.layouts.page-header')
            <div class="main-container">
                @include('admin.layouts.alerts')
                <div class="row gutters">
                    <div class="col-12">
                        <div class="card mb-3">
                            <div class="card-header d-flex justify-content-between align-items-center">
                                <div>
                                    <h5 class="mb-0">{{ $report->name }}</h5>
                                    <small class="text-muted">{{ __('Report type:') }} {{ ucfirst(str_replace('-', ' ', $report->type)) }}</small>
                                </div>
                                <div class="d-flex gap-2">
                                    <a href="{{ route('admin.reports.index', ['lang' => $lang]) }}" class="btn btn-light btn-sm">{{ __('Back to reports') }}</a>
                                    <a href="{{ route('admin.reports.download', ['lang' => $lang, 'report' => $report->id]) }}" class="btn btn-primary btn-sm">{{ __('Download CSV') }}</a>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="row g-3">
                                    <div class="col-md-3">
                                        <h6 class="text-muted">{{ __('Generated by') }}</h6>
                                        <p class="mb-0">{{ optional($report->generator)->name ?? __('System') }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <h6 class="text-muted">{{ __('Created at') }}</h6>
                                        <p class="mb-0">{{ optional($report->created_at)->format('Y-m-d H:i') }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <h6 class="text-muted">{{ __('Total records') }}</h6>
                                        <p class="mb-0">{{ $report->data['total_logs'] ?? count($rows) }}</p>
                                    </div>
                                    <div class="col-md-3">
                                        <h6 class="text-muted">{{ __('Generated at') }}</h6>
                                        <p class="mb-0">{{ $report->data['generated_at'] ?? '—' }}</p>
                                    </div>
                                </div>
                                @if (!empty($report->filters))
                                    <div class="mt-3">
                                        <h6 class="text-muted">{{ __('Applied filters') }}</h6>
                                        <ul class="list-inline mb-0">
                                            @foreach ($report->filters as $key => $value)
                                                <li class="list-inline-item badge bg-light text-dark">{{ ucfirst(str_replace('_', ' ', $key)) }}: {{ $value }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="card">
                            <div class="card-header">
                                <h5 class="mb-0">{{ __('Report data') }}</h5>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    @php $isScreenUptime = $report->type === 'screen-uptime'; @endphp
                                    <table class="table table-striped align-middle">
                                        <thead>
                                            <tr>
                                                @if ($isScreenUptime)
                                                    <th>{{ __('Screen ID') }}</th>
                                                    <th>{{ __('Code') }}</th>
                                                    <th>{{ __('Place') }}</th>
                                                    <th>{{ __('Online events') }}</th>
                                                    <th>{{ __('Offline events') }}</th>
                                                    <th>{{ __('Last status') }}</th>
                                                    <th>{{ __('Period start') }}</th>
                                                    <th>{{ __('Period end') }}</th>
                                                @else
                                                    <th>{{ __('Ad ID') }}</th>
                                                    <th>{{ __('Ad title') }}</th>
                                                    <th>{{ __('Plays') }}</th>
                                                    <th>{{ __('Total duration (seconds)') }}</th>
                                                    <th>{{ __('Screens') }}</th>
                                                @endif
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @forelse ($rows as $row)
                                                <tr>
                                                    @if ($isScreenUptime)
                                                        <td>{{ $row['screen_id'] ?? '—' }}</td>
                                                        <td>{{ $row['screen_code'] ?? '—' }}</td>
                                                        <td>{{ $row['place'] ?? '—' }}</td>
                                                        <td>{{ $row['online_events'] ?? 0 }}</td>
                                                        <td>{{ $row['offline_events'] ?? 0 }}</td>
                                                        <td>{{ $row['last_status'] ?? '—' }}</td>
                                                        <td>{{ $row['period_start'] ?? '—' }}</td>
                                                        <td>{{ $row['period_end'] ?? '—' }}</td>
                                                    @else
                                                        <td>{{ $row['ad_id'] ?? '—' }}</td>
                                                        <td>{{ $row['ad_title'] ?? '—' }}</td>
                                                        <td>{{ $row['plays'] ?? 0 }}</td>
                                                        <td>{{ $row['total_duration'] ?? 0 }}</td>
                                                        <td>{{ implode(', ', $row['screens'] ?? []) }}</td>
                                                    @endif
                                                </tr>
                                            @empty
                                                <tr>
                                                    <td colspan="{{ $isScreenUptime ? 8 : 5 }}" class="text-center text-muted">{{ __('No data available for this report.') }}</td>
                                                </tr>
                                            @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
